#!/usr/bin/env python3
import csv, sys
import pandas
import seaborn as sns
import matplotlib.pyplot as plt

from pprint import pprint

def read():
    df = pandas.read_csv('sleepdata.csv', sep=';')
    df.columns = ['start', 'end', 'quality', 'duration', 'wake', 'notes', 'heartrate', 'steps']
    return df

def plot(df):
    #sns.barplot(x='index', y='quality', data=df)
    #plt.show()
    pass

def main():
    df = read()
    print(df)
    plot(df)
    return 0

if __name__ == '__main__':
    sys.exit(main())
