#!/usr/bin/env python3
import csv, sys
import pandas
import datetime
import seaborn as sns
import matplotlib.pyplot as plt

from pprint import pprint

def read():
    df = pandas.read_csv('sleepdata.csv', sep=';')
    df.columns = ['start', 'end', 'quality', 'duration', 'wake', 'notes', 'heartrate', 'steps']
    df = df.infer_objects()
    read_percent = lambda s : int(s[:-1])
    read_time = lambda s : datetime.datetime.strptime(s, '%Y-%m-%d %H:%M:%S')
    read_duration = lambda s : datetime.datetime.strptime(s, '%H:%M')
    df['quality'] = df['quality'].apply(read_percent)
    df['start'] = df['start'].apply(read_time)
    df['end'] = df['end'].apply(read_time)
    df['duration'] = df['duration'].apply(read_duration)
    print(df.dtypes)

    return df

def plot(df):
    sns.barplot(x=list(range(len(df['start']))), y='quality', data=df)
    plt.xticks(rotation=90)
    plt.tight_layout()
    plt.show()

def main():
    df = read()
    print(df)
    plot(df)
    return 0

if __name__ == '__main__':
    sys.exit(main())
